name: Build P4EXP
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Env Vars
      run: |
        p4 set P4PORT=your_server:1666
        p4 set P4CLIENT=ci_workspace
        p4 set P4USER=ci_user

    - name: Download P4API.NET
      run: |
        curl -L -o p4api.zip "https://mirror.ghproxy.com/ftp.perforce.com/r23.2/bin.ntx64/p4api_vs2015_dyn.zip"
        unzip p4api.zip -d p4api_temp
        mkdir libs
        cp p4api_temp/p4api.net/lib/net452/* libs/

    - name: Build Project
      uses: microsoft/setup-msbuild@v1
      run: |
        nuget restore P4EXP.sln
        msbuild P4EXP/P4EXP.csproj /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: p4exp-release
        path: P4EXP/bin/x64/Release/
