name: CI – Build P4EXP Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet --info
          dotnet restore P4EXP.sln

      - name: Build project
        run: dotnet build P4EXP.sln --configuration Release

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Compile WiX Bundle
        run: |
          candle.exe installer/Bundle.wxs -o installer/Bundle.wixobj -ext WixBalExtension
          light.exe installer/Bundle.wixobj -o installer/output/Setup.exe -ext WixBalExtension

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: P4EXP-Setup
          path: installer/output/Setup.exe
